#!/bin/sh

make(){
  f=$(mktemp -p $1)
  dd if=/dev/urandom of=$f count=64 bs=1
}

rm -rf test-dir
mkdir test-dir
mkdir test-dir/sub1
make test-dir
make test-dir
make test-dir
make test-dir/sub1
make test-dir/sub1
make test-dir/sub1

genisoimage -o test.iso test-dir
